import type { Metadata } from "next";

import "./globals.css";

import { Roboto } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import AppProvider from "@/app/app-provider";
import { cookies } from "next/headers";
import SlideSession from "@/components/slide-session";
import accountApiRequest from "@/apiRequests/account";
import { AccountResType } from "@/schemaValidation/account.schema";
const roboto = Roboto({
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const sessionToken = (await cookieStore).get("sessionToken");
    
    let user: AccountResType["data"] | null = null;
    if (sessionToken) {
        const data = await accountApiRequest.me(sessionToken.value);
        user = data.payload.data;
    }
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={roboto.className}>
                <Toaster />
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AppProvider
                        inititalSessionToken={sessionToken?.value}
                        user={user}
                    >
                        <Header user={user} />
                        {children}
                        <SlideSession />
                    </AppProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
